AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: vdf-swwiper-sqs

Resources:
  Swwiper::
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: ../../src
      Description: vdf-swwiper-sqs
      MemorySize: 1024
      Timeout: 300
      Role: arn:aws:iam::322501851660:role/vdf-swwiper-lambda-exec-role
      # Events:
      #   EventsDevDataMasteryNewMathAdaptivePacket:
      #     Type: SNS
      #     Properties:
      #       Topic: TopicArn

      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-11111111
      #   SubnetIds:
      #     - subnet-cccccccc
      #     - subnet-dddddddd
      #     - subnet-99999999
      Environment:
        Variables:
          VAR_NAME: var_value

  # SubscriptionNam:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     Protocol: lambda
  #     Endpoint: !GetAtt
  #       - AdaptivePacketHandler
  #       - Arn
  #     TopicArn: TopicArn
